title: Janice Ding # your name (or website title) here
logo: "/images/IMG_E7536 github.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently undertaking the Associate Data Analyst programme with NTUC LearningHub.
  The data analysis projects which I've worked on are shared in my Portfolio. 
  <br><br>
  Area of interest:
  Power Query, Power Pivot, Power BI, Interactive Dashboard, SQL 
  <br><br>
  <a href="https://www.linkedin.com/in/janiceding">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
